[package]
name = "risotto"
version = "0.1.0"
authors = ["Sergey Orlovsky <sergey@test2trade.com>"]

[dependencies]
#openssl =  { path = "/Users/sergey/code/rust/rust-openssl/openssl" }
openssl = "0.9"
flate2 = { version = "0.2", features = ["zlib"]}
time = "0.1"
